# Generated by Django 5.0.6 on 2024-05-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='genders',
        ),
    ]
