# Generated by Django 5.0.6 on 2024-05-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klmsapp', '0003_alter_gender_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='genders',
        ),
    ]
