# Generated by Django 5.0.6 on 2024-05-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klmsapp', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
